---
version: '3.2'

services:
  build_deployment_package:
    build: .
    # This uses the value of the LAMBDA_TAG environment variable from
    # the invoking environment but falls back to a default value.
    image: cisagov/nvdsync_lambda:${LAMBDA_TAG:-latest}
    entrypoint: /opt/build_artifact.sh
    environment:
      # This uses the value of the BUILD_FILE_NAME environment variable
      # from the invoking environment but falls back to a default value.
      - BUILD_FILE_NAME=${BUILD_FILE_NAME:-lambda_build.zip}
    volumes:
      - ./src/build_artifact.sh:/opt/build_artifact.sh
      - .:/var/task/output
  run_lambda_locally:
    build: .
    # This uses the value of the LAMBDA_TAG environment variable from
    # the invoking environment but falls back to a default value.
    image: cisagov/nvdsync_lambda:${LAMBDA_TAG:-latest}
    environment:
      - AWS_LAMBDA_FUNCTION_TIMEOUT=900000
      - AWS_LAMBDA_FUNCTION_MEMORY_SIZE=10240
    depends_on:
      - mongo
    ports:
      - "9000:8080"
  mongo:
    image: mongo:3.6.23
    ports:
      - "37017:27017"
